name: Generate and Deploy TypeDoc

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "src/**/*"
      - "typedoc.json"
      - "tsconfig.json"
      - "package.json"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Type Check
        run: npm run typecheck

      - name: Generate TypeDoc
        run: npm run docs

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/typedoc
